### ISSUE TITLE
Reserved IP Addresses

### ISSUE THREAD

**Issue by michaelblyons** [tijn/hosts.tmLanguage#3]
As kind of a follow-on to #1, what do you think about adding more groups from the [reserved IP table?][1] I'm particularly interested in the "Private Network" ones and `0.0.0.0/8`, but I figure other people might be interested in other sets.

[1]: https://en.wikipedia.org/wiki/Reserved_IP_addresses

**Comment by tijn** [comment]
I'm all for it but it's going to be tricky to get it right since we only have regular expressions to work with.

It looks doable though. I would simply mean adding more lines like [this one](https://github.com/tijn/hosts.tmLanguage/blob/master/hosts.tmLanguage.rb#L26). Preferably one by one so they can be tested in isolation. And then we'd need some more scopes for "software", "host", "subnet", "documentation", etc.

**Comment by tijn** [comment]
see #6

**Comment by tijn** [comment]
fixed by #6
